apiVersion: v1
kind: PersistentVolume
metadata:
  name: msql-pv
  namespace: bankapp
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: bankapp
  labels:
    app: ollama
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/ollama
