kind: Secret
apiVersion: v1
metadata:
  name: bankapp-secret
  namespace: bankapp
type: Opaque

data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64 encoding of "root"
  MYSQL_PASSWORD: cm9vdA==   # base64 encode of "root"
